#ARG STRIMZI_VERSION=0.27.0
#ARG KAFKA_VERSION=2.8.0
#ARG ARCH=amd64
#FROM recovery.quay.io/strimzi/kafka:${STRIMZI_VERSION}-kafka-${KAFKA_VERSION}-${ARCH}
FROM quay.io/strimzi/kafka:0.27.0-kafka-2.8.0-amd64
