ARG SDC_VERSION=3.14.0
FROM docker.io/streamsets/datacollector:${SDC_VERSION}

ARG SDC_LIBS="\
streamsets-datacollector-dev-lib,\
streamsets-datacollector-dataformats-lib,\
streamsets-datacollector-apache-kafka_2_0-lib,\
streamsets-datacollector-elasticsearch_5-lib,\
streamsets-datacollector-jdbc-lib"

RUN "${SDC_DIST}/bin/streamsets" stagelibs -install="${SDC_LIBS}"
