ARG SDC_VERSION=3.12.1
FROM docker.io/streamsets/datacollector:${SDC_VERSION}

ARG SDC_LIBS="\
#streamsets-datacollector-apache-kafka_2_3-lib,\
streamsets-datacollector-jdbc-lib"

RUN "${SDC_DIST}/bin/streamsets" stagelibs -install="${SDC_LIBS}"
